angular.module('tombola.snapCardGame.GameModel',[]);
angular.module('tombola.snapCardGame.DeckService',[]);
angular.module('tombola.snapCardGame.controller',[]);
angular.module('tombola.snapCardGame.directives',[]);
angular.module('tombola.snapCardGame',[
    'tombola.snapCardGame.GameModel',
    'tombola.snapCardGame.DeckService',
    'tombola.snapCardGame.controller',
    'tombola.snapCardGame.directives'
]);
